import './ModalOverlay.css'
import './DisclaimerModal.css'

interface DisclaimerModalProps {
  onClose: () => void
}

export default function DisclaimerModal({ onClose }: DisclaimerModalProps) {
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="disclaimer-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Disclaimer</h2>
          <button onClick={onClose} className="close-btn">×</button>
        </div>
        <div className="modal-content">
          <p className="last-updated">Last updated: {new Date().toLocaleDateString()}</p>
          
          <section className="important-notice">
            <div className="notice-box">
              <span className="warning-icon">⚠️</span>
              <div>
                <h3>Important Notice</h3>
                <p>
                  <strong>DoctorAibolit is NOT a medical service, therapy service, or medical treatment.</strong>
                </p>
              </div>
            </div>
          </section>

          <section>
            <h3>1. Not a Medical Service</h3>
            <p>
              DoctorAibolit provides AI-powered health information and wellness guidance only. 
              It is not intended to diagnose, treat, cure, or prevent any medical condition, 
              mental health disorder, or psychological condition.
            </p>
          </section>

          <section>
            <h3>2. Not a Substitute for Professional Care</h3>
            <p>
              This service is NOT a substitute for professional medical advice, diagnosis, 
              or treatment. Always seek the advice of qualified health providers with any 
              questions you may have regarding a medical or mental health condition.
            </p>
            <p>
              If you are experiencing a medical emergency, mental health crisis, or 
              suicidal thoughts, please contact emergency services immediately:
            </p>
            <ul>
              <li><strong>Emergency Services:</strong> 911 (US) or your local emergency number</li>
              <li><strong>Suicide Prevention Lifeline:</strong> 988 (US)</li>
              <li><strong>Crisis Text Line:</strong> Text HOME to 741741</li>
            </ul>
          </section>

          <section>
            <h3>3. AI Limitations</h3>
            <p>
              The AI responses are generated by artificial intelligence and may not always 
              be accurate, appropriate, or suitable for your specific situation. The AI 
              does not have access to your complete medical history or personal circumstances.
            </p>
          </section>

          <section>
            <h3>4. No Therapeutic Relationship</h3>
            <p>
              Using DoctorAibolit does not create a doctor-patient, therapist-client, or 
              any other professional relationship. The service is provided for informational 
              and supportive purposes only.
            </p>
          </section>

          <section>
            <h3>5. User Responsibility</h3>
            <p>
              You are solely responsible for your use of this service and any decisions 
              you make based on information provided. We are not liable for any outcomes 
              resulting from your use of DoctorAibolit.
            </p>
          </section>

          <section>
            <h3>6. No Guarantees</h3>
            <p>
              We make no guarantees about the effectiveness, accuracy, or suitability of 
              the information or support provided by DoctorAibolit. Results may vary 
              depending on individual circumstances.
            </p>
          </section>

          <section>
            <h3>7. Content Accuracy</h3>
            <p>
              While we strive to provide helpful and accurate information, we cannot 
              guarantee that all AI-generated responses are correct, complete, or up-to-date.
            </p>
          </section>

          <section>
            <h3>8. Limitation of Liability</h3>
            <p>
              To the fullest extent permitted by law, DoctorAibolit and its operators 
              shall not be liable for any direct, indirect, incidental, special, 
              consequential, or punitive damages arising from your use of this service.
            </p>
          </section>

          <section>
            <h3>9. When to Seek Professional Help</h3>
            <p>You should seek professional medical or mental health care if you experience:</p>
            <ul>
              <li>Severe symptoms or medical emergencies</li>
              <li>Depression or suicidal thoughts</li>
              <li>Substance abuse issues</li>
              <li>Any symptoms that interfere with daily life</li>
              <li>Concerns about your mental or physical health</li>
            </ul>
          </section>

          <section>
            <h3>10. Acceptance of Terms</h3>
            <p>
              By using DoctorAibolit, you acknowledge that you have read, understood, 
              and agree to this disclaimer. If you do not agree, please do not use this service.
            </p>
          </section>

          <section>
            <h3>11. Contact</h3>
            <p>
              If you have questions about this disclaimer, please contact us through 
              our contact form.
            </p>
          </section>
        </div>
        <div className="modal-footer">
          <button onClick={onClose} className="modal-close-button">Close</button>
        </div>
      </div>
    </div>
  )
}

