import { Link } from 'react-router-dom'
import './Disclaimer.css'

export default function Disclaimer() {
  return (
    <div className="disclaimer-page">
      <div className="disclaimer-container">
        <Link to="/" className="back-btn">← Back to Home</Link>
        <h1>Disclaimer</h1>
        <p className="last-updated">Last updated: {new Date().toLocaleDateString()}</p>
        
        <section className="important-notice">
          <h2>⚠️ Important Notice</h2>
          <p>
            <strong>DoctorAibolit is NOT a medical service, therapy service, or medical treatment.</strong>
          </p>
        </section>

        <section>
          <h2>1. Not a Medical Service</h2>
          <p>
            DoctorAibolit provides AI-powered health information and wellness guidance only. 
            It is not intended to diagnose, treat, cure, or prevent any medical condition, 
            mental health disorder, or psychological condition.
          </p>
        </section>

        <section>
          <h2>2. Not a Substitute for Professional Care</h2>
          <p>
            This service is NOT a substitute for professional medical advice, diagnosis, 
            or treatment. Always seek the advice of qualified health providers with any 
            questions you may have regarding a medical or mental health condition.
          </p>
          <p>
            If you are experiencing a medical emergency, mental health crisis, or 
            suicidal thoughts, please contact emergency services immediately:
          </p>
          <ul>
            <li><strong>Emergency Services:</strong> 911 (US) or your local emergency number</li>
            <li><strong>Suicide Prevention Lifeline:</strong> 988 (US)</li>
            <li><strong>Crisis Text Line:</strong> Text HOME to 741741</li>
          </ul>
        </section>

        <section>
          <h2>3. AI Limitations</h2>
          <p>
            The AI responses are generated by artificial intelligence and may not always 
            be accurate, appropriate, or suitable for your specific situation. The AI 
            does not have access to your complete medical history or personal circumstances.
          </p>
        </section>

        <section>
          <h2>4. No Therapeutic Relationship</h2>
          <p>
            Using DoctorAibolit does not create a doctor-patient, therapist-client, or 
            any other professional relationship. The service is provided for informational 
            and supportive purposes only.
          </p>
        </section>

        <section>
          <h2>5. User Responsibility</h2>
          <p>
            You are solely responsible for your use of this service and any decisions 
            you make based on information provided. We are not liable for any outcomes 
            resulting from your use of DoctorAibolit.
          </p>
        </section>

        <section>
          <h2>6. No Guarantees</h2>
          <p>
            We make no guarantees about the effectiveness, accuracy, or suitability of 
            the information or support provided by DoctorAibolit. Results may vary 
            depending on individual circumstances.
          </p>
        </section>

        <section>
          <h2>7. Content Accuracy</h2>
          <p>
            While we strive to provide helpful and accurate information, we cannot 
            guarantee that all AI-generated responses are correct, complete, or up-to-date.
          </p>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, DoctorAibolit and its operators 
            shall not be liable for any direct, indirect, incidental, special, 
            consequential, or punitive damages arising from your use of this service.
          </p>
        </section>

        <section>
          <h2>9. When to Seek Professional Help</h2>
          <p>You should seek professional medical or mental health care if you experience:</p>
          <ul>
            <li>Severe symptoms or medical emergencies</li>
            <li>Depression or suicidal thoughts</li>
            <li>Substance abuse issues</li>
            <li>Any symptoms that interfere with daily life</li>
            <li>Concerns about your mental or physical health</li>
          </ul>
        </section>

        <section>
          <h2>10. Acceptance of Terms</h2>
          <p>
            By using DoctorAibolit, you acknowledge that you have read, understood, 
            and agree to this disclaimer. If you do not agree, please do not use this service.
          </p>
        </section>

        <section>
          <h2>11. Contact</h2>
          <p>
            If you have questions about this disclaimer, please contact us through 
            our <a href="/contact">contact form</a>.
          </p>
        </section>
      </div>
    </div>
  )
}

